version: '3'
services:
  filebeat:
    hostname: filebeat-host
    container_name: filebeat-host
    build: 
      context: .
      dockerfile: Filebeat-Dockerfile
    networks:
      - lsnetwork
  logstash:
    hostname: ls-adx
    container_name: ls-adx
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - logstash_version=8.8.2
    env_file:
      - ./conf/.env
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    command: logstash -f /usr/share/logstash/pipeline/logstash-kusto.config
    networks:
      - lsnetwork
networks:
  lsnetwork:
    driver: bridge