# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar'
  require 'net/minidev/json-smart/2.3/json-smart-2.3.jar'
  require 'com/microsoft/azure/kusto/kusto-data/2.1.2/kusto-data-2.1.2.jar'
  require 'org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar'
  require 'com/fasterxml/jackson/core/jackson-databind/2.9.10.7/jackson-databind-2.9.10.7.jar'
  require 'commons-codec/commons-codec/1.14/commons-codec-1.14.jar'
  require 'com/microsoft/azure/kusto/kusto-ingest/2.1.2/kusto-ingest-2.1.2.jar'
  require 'org/jetbrains/annotations/17.0.0/annotations-17.0.0.jar'
  require 'com/microsoft/azure/azure-storage/8.3.0/azure-storage-8.3.0.jar'
  require 'com/google/code/gson/gson/2.8.0/gson-2.8.0.jar'
  require 'javax/activation/activation/1.1/activation-1.1.jar'
  require 'net/minidev/accessors-smart/1.2/accessors-smart-1.2.jar'
  require 'com/microsoft/azure/adal4j/1.6.5/adal4j-1.6.5.jar'
  require 'com/nimbusds/nimbus-jose-jwt/9.1.4/nimbus-jose-jwt-9.1.4.jar'
  require 'com/fasterxml/jackson/core/jackson-annotations/2.9.10/jackson-annotations-2.9.10.jar'
  require 'org/ow2/asm/asm/5.0.4/asm-5.0.4.jar'
  require 'com/sun/mail/javax.mail/1.6.1/javax.mail-1.6.1.jar'
  require 'com/nimbusds/oauth2-oidc-sdk/6.5/oauth2-oidc-sdk-6.5.jar'
  require 'org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar'
  require 'org/apache/httpcomponents/httpcore/4.4.11/httpcore-4.4.11.jar'
  require 'com/nimbusds/lang-tag/1.5/lang-tag-1.5.jar'
  require 'com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar'
  require 'com/univocity/univocity-parsers/2.1.1/univocity-parsers-2.1.1.jar'
  require 'com/microsoft/azure/azure-keyvault-core/1.0.0/azure-keyvault-core-1.0.0.jar'
  require 'com/google/guava/guava/20.0/guava-20.0.jar'
  require 'commons-logging/commons-logging/1.2/commons-logging-1.2.jar'
  require 'org/json/json/20190722/json-20190722.jar'
  require 'org/apache/httpcomponents/httpclient/4.5.8/httpclient-4.5.8.jar'
end

if defined? Jars
  require_jar 'com.github.stephenc.jcip', 'jcip-annotations', '1.0-1'
  require_jar 'net.minidev', 'json-smart', '2.3'
  require_jar 'com.microsoft.azure.kusto', 'kusto-data', '2.1.2'
  require_jar 'org.apache.commons', 'commons-lang3', '3.9'
  require_jar 'com.fasterxml.jackson.core', 'jackson-databind', '2.9.10.7'
  require_jar 'commons-codec', 'commons-codec', '1.14'
  require_jar 'com.microsoft.azure.kusto', 'kusto-ingest', '2.1.2'
  require_jar 'org.jetbrains', 'annotations', '17.0.0'
  require_jar 'com.microsoft.azure', 'azure-storage', '8.3.0'
  require_jar 'com.google.code.gson', 'gson', '2.8.0'
  require_jar 'javax.activation', 'activation', '1.1'
  require_jar 'net.minidev', 'accessors-smart', '1.2'
  require_jar 'com.microsoft.azure', 'adal4j', '1.6.5'
  require_jar 'com.nimbusds', 'nimbus-jose-jwt', '9.1.4'
  require_jar 'com.fasterxml.jackson.core', 'jackson-annotations', '2.9.10'
  require_jar 'org.ow2.asm', 'asm', '5.0.4'
  require_jar 'com.sun.mail', 'javax.mail', '1.6.1'
  require_jar 'com.nimbusds', 'oauth2-oidc-sdk', '6.5'
  require_jar 'org.slf4j', 'slf4j-api', '1.8.0-beta4'
  require_jar 'org.apache.httpcomponents', 'httpcore', '4.4.11'
  require_jar 'com.nimbusds', 'lang-tag', '1.5'
  require_jar 'com.fasterxml.jackson.core', 'jackson-core', '2.9.4'
  require_jar 'com.univocity', 'univocity-parsers', '2.1.1'
  require_jar 'com.microsoft.azure', 'azure-keyvault-core', '1.0.0'
  require_jar 'com.google.guava', 'guava', '20.0'
  require_jar 'commons-logging', 'commons-logging', '1.2'
  require_jar 'org.json', 'json', '20190722'
  require_jar 'org.apache.httpcomponents', 'httpclient', '4.5.8'
end
