name: build

on:
  push:

jobs:
  build:
    name: Build gem
    runs-on: ubuntu-latest
    environment: build
    permissions:
      checks: write
      pull-requests: write
      id-token: write
      contents: read
    strategy:
      matrix:
        logstash: [
          { version: '8.7.0', url: "https://artifacts.elastic.co/downloads/logstash/logstash-8.7.0-linux-x86_64.tar.gz" , main: 'true' }
        ]
    env:
      LOGSTASH_SOURCE: 1
      LOGSTASH_PATH: /home/runner/logstash
      JRUBY_HOME: /home/runner/logstash/vendor/jruby
      JAVA_HOME: /home/runner/logstash/jdk
    steps:
      - name: Build logstash
        run: |
          echo "Getting logstash version ${{matrix.logstash.version}}"
          wget -O logstash.tar.gz ${{matrix.logstash.url}}
          tar -xf logstash.tar.gz
          mv logstash*/ logstash
        working-directory: /home/runner
      - name: Set Path
        run: |
          echo "$LOGSTASH_PATH/bin" >> $GITHUB_PATH
          echo "$LOGSTASH_PATH/vendor/jruby/bin" >> $GITHUB_PATH
      - name: Install bundler
        run: jruby -S gem install bundler -v 2.4.19
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: 'kusto'
      - name: List CWD
        run: ls -al
        working-directory: 'kusto' 
      - run: jruby -S bundle install
        working-directory: 'kusto'
      - name: Run gradle vendor
        run: ./gradlew vendor
        working-directory: 'kusto'        
      - name: Run unit tests
        run: jruby -S bundle exec rspec -r rspec_junit_formatter --format RspecJunitFormatter -o rspec.xml
        working-directory: 'kusto'
      - run: jruby -S gem build *.gemspec
        working-directory: 'kusto'
      - run: mv *.gem logstash-kusto.gem
        working-directory: 'kusto'
      - if: matrix.logstash.main == 'true'
        name: Upload gem
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: logstash-kusto.gem
          path: 'kusto/logstash-kusto.gem'
      - if: matrix.logstash.main == 'true'
        name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@4e7013f9576bd22ffdae979dc6e68cb9ec2aeece # v2.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: kusto/rspec.xml
