on:
  workflow_dispatch:  
  release:
    types: [released]

name: Deploy and Create Release

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      id-token: write 
      packages: write # for pushing GitHub packages
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@bec3f19a76460dbe12f60def7d1a77585f07516c # v1.322.0
        with:
          ruby-version: jruby
          bundler-cache: true
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run gradle vendor
        run: ./gradlew vendor
      - name: Build gem
        run: jruby -S gem build *.gemspec
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@74c3d60f5a28f358ccf241a00c9021ea16f0569f # v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Publish gem
        uses: dawidd6/action-publish-gem@c4713bf1595e0686322d6cf6c1a1c0dcaeca55de # v1.2.0
        with:
          api_key: ${{secrets.RUBYGEMS_KEY}}
          github_token: ${{secrets.GITHUB_TOKEN}}
      - name: Set artifact name
        id: set_artifact_name
        run: |
          ARTIFACT_PATH=$(find . -maxdepth 1 -iname '*.gem')
          echo "::set-output name=artifact_name::$ARTIFACT_PATH"
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5 # v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./${{ steps.set_artifact_name.outputs.artifact_name }}
          asset_name: ${{ steps.set_artifact_name.outputs.artifact_name }}
          asset_content_type: application/zip
